### ISSUE TITLE
Modify prokka to add fsa output

### ISSUE THREAD

**Issue by DrB-S** [UPHL-BioNGS/Grandeur#109]
Prokka can produce AA translations of coding regions in the sample genomes. That would be helpful for incorporating SnpEff and other tools to examine effects of sequence modifications.

**Comment by DrB-S** [comment]
That's faa output....

**Comment by erinyoung** [comment]
Oh no! The `.faa` file should be there when you run the workflow! The `.fsa` should be there, too.

Is the faa file not showing up when you run the workflow!?!?!


Here is are the files that should be generated via prokka:
```
├── prokka                                                                        
│   └── sample
│       ├── sample.err
│       ├── sample.faa
│       ├── sample.ffn
│       ├── sample.fna
│       ├── sample.fsa
│       ├── sample.gbk
│       ├── sample.gff                                                             
│       ├── sample.log
│       ├── sample.sqn
│       ├── sample.tbl
│       ├── sample.tsv
│       └── sample.txt
```

**Comment by DrB-S** [comment]
Sorry about that! Yes, you are correct! I don't know why I didn't see those files in the prokka dir before!
