### ISSUE TITLE
datasets_download error

### ISSUE THREAD

**Issue by whottel** [UPHL-BioNGS/Grandeur#116]
Hello,

I am running into an error with the average_nucleotide_identity:datasets_download process.
I am using grandeur version 3.3.20230815, and I am wondering if something changed on NCBI's sides as I have run grandeur on the same datasets as recently as last week without issue and have not updated anything in the interim.
Please find attached the relevant section of the Nextflow log.
[datasets_download_error.txt](https://github.com/UPHL-BioNGS/Grandeur/files/12542775/datasets_download_error.txt)

Thanks,
Wes

**Comment by erinyoung** [comment]
I recognize this error. You likely lost internet connection. Or it became weaker. Or NCBI lost internet connection. Or someone on a cruise off the coast of Alaska sneezed.

Trouble shooting steps that I would do:
1. attempt with `resume`. Basically, just use whatever command you used before and add the `-resume` flag.
2. if this error happens again with `-resume`, then I suggest setting `params.current_datasets  = false` - which is likely going to be the default in a future release. This will cause Grandeur to use the reference genomes from the github repo with fastani. 
2a. If the included reference isn't comprehensive enough, you can create your own fastani reference (instructions here: https://github.com/UPHL-BioNGS/Grandeur/wiki/fastani)

**Comment by whottel** [comment]
Hi Erin,
I was also thinking there might be a connection issue. I have tried running grandeur multiple times on different days including with resume and continued to get the same error.
At any rate, I followed your second suggestion and it looks like the pipeline completed as normal.
Thanks,
Wes

**Comment by erinyoung** [comment]
I wanted to let you know that the version of grandeur that is currently going through testing (https://github.com/UPHL-BioNGS/Grandeur/pull/124) has datasets set to false by default. Let me know if there should be additional reference genomes for the organisms that you sequences. A list of genomes included with the workflow can be found at [assets/included_genomes.txt](https://github.com/UPHL-BioNGS/Grandeur/pull/124/files#diff-aa1a04e2a01f733435d1cb3f7763863d37e7a1267ee041860577420190ed0757).

I'm hoping to release this version tonight or early tomorrow.
