### ISSUE TITLE
Resume analysis after interruption without rerunning spades and others

### ISSUE THREAD

**Issue by DrB-S** [UPHL-BioNGS/Grandeur#128]
I ran a Grandeur analysis yesterday that was interrupted. When I used '-resume' to continue, it restarted spades alignment, even though that alignment had previously finished, along with mash, mlst, and quast, all of which had produced results.  Is there a way to resume an analysis without rerunning specific processes?

**Comment by erinyoung** [comment]
nextflow probably just didn't save everything correctly, and so didn't know that it had already done those steps.

nextflow's `-resume` is the best way to continue, and I don't have any tips or tricks if that doesn't work.

**Comment by DrB-S** [comment]
OK. Thanks.
