### ISSUE TITLE
Allow for no fastani hits

### ISSUE THREAD

**Issue by erinyoung** [UPHL-BioNGS/Grandeur#130]
I didn't test for a sequencing run that didn't have any fastani hits

https://github.com/UPHL-BioNGS/Grandeur/issues/129#issuecomment-1745554756

**Comment by erinyoung** [comment]
This issue remains in https://github.com/UPHL-BioNGS/Grandeur/pull/134, the line https://github.com/UPHL-BioNGS/Grandeur/pull/134/files#diff-26f116b8515a5c1efe98b036fdf3d674a43aa9c6138d1bb8cbf2dd8813b73432R19 and will cause failure if there is no fastani top hits among the input samples.

This error only occurs if `params.msa = true` AND there are no fastani top hits in all the samples. 

There are two current workarounds for this error:
1. Use a user-supplied fastani reference. Instructions on how to add in references for fastani are found in the fastani wiki page : https://github.com/UPHL-BioNGS/Grandeur/wiki/fastani
2. Skip top hit incorporation by setting `params.fastani_include  = false`

**Comment by DrB-S** [comment]
Where does that code snippet go?

**Comment by erinyoung** [comment]
https://github.com/UPHL-BioNGS/Grandeur/pull/134/files#diff-26f116b8515a5c1efe98b036fdf3d674a43aa9c6138d1bb8cbf2dd8813b73432R19 , where the file undergoes a mapping step.

**Comment by erinyoung** [comment]
I think this latest PR is going to fix your issue: https://github.com/UPHL-BioNGS/Grandeur/pull/138

Hopefully....

Let me know if you run into issues!!!
