### ISSUE TITLE
Uncommitted changes blocking repository pull

### ISSUE THREAD

**Issue by DrB-S** [UPHL-BioNGS/Grandeur#164]
I receive the following with a pull request for Grandeur:

$ nextflow pull UPHL-BioNGS/Grandeur
Checking UPHL-BioNGS/Grandeur ...
UPHL-BioNGS/Grandeur contains uncommitted changes -- cannot pull from repository

**Comment by erinyoung** [comment]
That's a nextflow error. The easiest way I've found to resolve this is to delete your local copy, which is likely at `~/.nextflow/assets/UPHL-BioNGS/Grandeur`.

The command is something like
```
rm -rf ~/.nextflow/assets/UPHL-BioNGS/Grandeur
```

**Comment by DrB-S** [comment]
That worked.
