### ISSUE TITLE
MultiQC not pulling in Mashtree or Heat Cluster images anymore

### ISSUE THREAD

**Issue by hutchinsonmiri** [UPHL-BioNGS/Grandeur#174]
Hi there! I am not sure if this is user error on my part but I am not seeing the Mashtree and SNP matrix in the MultiQC file anymore. It was working back in January but sadly quit working recently. Not sure if anyone else has had similar issues or if there is any way to adjust some setting to get them back. Not a huge issue though... Just wondering. Thanks in advance!!!

**Comment by erinyoung** [comment]
This is a huge issue! I will look into this

**Comment by hutchinsonmiri** [comment]
Thanks so much!!!!

**Comment by hutchinsonmiri** [comment]
Sorry for the late reply! I haven't been able to run the new pipeline yet
because the max cpus parameters in the config doesn't seem to be working.
Do you have any suggestions? Thanks for all your help!!!

**Comment by erinyoung** [comment]
I do have some suggestions, but you're not going to like them.

We had to make some adjustments to Grandeur so it would compatible with nf-core config files, so we no longer have a maxcpu param.

What command / config file did you use before? Perhaps I could help you translate that into the current param scheme.

**Comment by hutchinsonmiri** [comment]
Haha, well, I am open to change! Currently, we have params.maxcpus set to 8.

**Comment by erinyoung** [comment]
In a config file, you're going to want something to set cpus a little lower than the defaults. It would look something like

```
process {
    withLabel:process_medium {
        cpus   = { 4     * task.attempt }
        memory = { 36.GB * task.attempt }
        time   = { 4.h   * task.attempt }
    }
    withLabel:process_high {
        cpus   = { 8 }
        memory = { 72.GB * task.attempt }
        time   = { 16.h  * task.attempt }
    }
}
```

And then you can use that in the workflow by using

```
nextflow run UPHL-BioNGS/Grandeur <all the stuff you normally use> -c new_config_file.config
```

**Comment by hutchinsonmiri** [comment]
Fantastic!!! Thanks for the help! I will try this when I run again tomorrow

**Comment by erinyoung** [comment]
this latest version of Grandeur _SHOULD_ fix this issue. I have noticed that sometimes the phytreeviz images are not next to each other in multiqc, so they may be difficult to find.
