### ISSUE TITLE
version.yml file in  v4.0.20240214

### ISSUE THREAD

**Issue by whottel** [UPHL-BioNGS/Grandeur#180]
Hello,

First of all thanks for all the improvements that you continue to make for grandeur.
We were testing v4.0.20240214 (run with Nextflow v 23.10.1 )  and noticed some issues with the versions.yml that is getting created. When running the pipeline, I see this versions.yml is created in the grandeur directory.
![Capture1](https://github.com/UPHL-BioNGS/Grandeur/assets/30357265/b33e6f1b-c1c9-4274-bca0-b8c687f3fe8b)

Not sure if this is intended to still be here, or if a cleanup step is not working properly. 

For other users  at our lab the pipeline is failing due to this file and is causing a nextflow error:

[error_log.txt](https://github.com/UPHL-BioNGS/Grandeur/files/14543922/error_log.txt)

**Comment by erinyoung** [comment]
Oh no!

versions.yml is something that all nf-core workflows have. They don't seem to run into errors and I should dig deeper into why.

I should have this fixed by next week!

**Comment by erinyoung** [comment]
It looks like I need to add `saveAs: { filename -> filename.equals('versions.yml') ? null : filename },` to publishDir

**Comment by erinyoung** [comment]
@whottel , my apologies for taking so long with this!

This issue should now be resolved. Let me know if my assumption is incorrect!

**Comment by whottel** [comment]
No worries, thanks for the update!
In initial tests it all seems to be working fine on our end.
