### ISSUE TITLE
mashtree failure

### ISSUE THREAD

**Issue by DrB-S** [UPHL-BioNGS/Grandeur#196]
Pulling Singularity image docker://staphb/mashtree:1.4.6 [cache /data/nextflow_cachedir/staphb-mashtree-1.4.6.img]
Pulling Singularity image docker://staphb/kleborate:2.4.1 [cache /data/nextflow_cachedir/staphb-kleborate-2.4.1.img]
Pulling Singularity image docker://staphb/ncbi-amrfinderplus:3.12.8-2024-01-31.1 [cache /data/nextflow_cachedir/staphb-ncbi-amrfinderplus-3.12.8-2024-01-31.1.img]
ERROR ~ Error executing process > 'phylogenetic_analysis:mashtree'

Caused by:
  Failed to pull singularity image
  command: singularity pull  --name staphb-mashtree-1.4.6.img.pulling.1715194943310 docker://staphb/mashtree:1.4.6 > /dev/null
  status : 255
  message:
    INFO:    Environment variable SINGULARITY_CACHEDIR is set, but APPTAINER_CACHEDIR is preferred
    INFO:    Converting OCI blobs to SIF format
    INFO:    Starting build...
    Getting image source signatures
    Copying blob sha256:595a0fe1a930d595b1bb1619f4f210a666a36522db2baf4078091c5bc2c195ba
    Copying blob sha256:9b4c911e1bd794a157d42a2078e0fff6ca56343f7e2aaef55446683497dd6db1
    Copying blob sha256:3e0f5a9f06fef2f919b49b617e6771f9a6881760a441982dff4d6219e140de5f
    Copying blob sha256:6da302ea23691726bc231ec4f1fc85654ae38567b65f92be0eff056ec1fec7fb
    Copying blob sha256:a486411936734b0d1d201c8a0ed8e9d449a64d5033fdc33411ec95bc26460efb
    Copying blob sha256:40fa5233cae50c8243acc9b78f6f165fbf9a9b0493bee7966a994768c1a9b47f
    Copying blob sha256:4f4fb700ef54461cfa02571ae0db9a0dc1e0cdb5577484a6d75e68dc38e8acc1
    Copying config sha256:d7b95427afe6292cfc5760512c210525704681987ec848c682725f3cf323f7e4
    Writing manifest to image destination
    FATAL:   While making image from oci registry: error fetching image to cache: while building SIF from layers: conveyor failed to get: while getting config: no descriptor found for reference "b35b874c94dd47fb479adedf45b768b78caa5e2bb48e9c4c8dcf44f01597926a"

**Comment by DrB-S** [comment]
Here is the command-line:
nextflow run UPHL-BioNGS/Grandeur -profile singularity,msa --reads reads --iqtree2_outgroup GCF_000240185.1

**Comment by erinyoung** [comment]
It looks like the image didn't pull correctly.

Can you try running the following?
```
singularity pull --name staphb-mashtree-1.4.6.img.pulling.1715194943310 docker://staphb/mashtree:1.4.6
mv staphb-mashtree-1.4.6.img.pulling.1715194943310 /data/nextflow_cachedir/staphb-mashtree-1.4.6.img
```

**Comment by DrB-S** [comment]
That seemed to work:
$ singularity pull --name staphb-mashtree-1.4.6.img.pulling.1715194943310 docker://staphb/mashtree:1.4.6
INFO:    Environment variable SINGULARITY_CACHEDIR is set, but APPTAINER_CACHEDIR is preferred
INFO:    Converting OCI blobs to SIF format
INFO:    Starting build...
Getting image source signatures
Copying blob 595a0fe1a930 skipped: already exists
Copying blob 3e0f5a9f06fe skipped: already exists
Copying blob 40fa5233cae5 skipped: already exists
Copying blob a48641193673 skipped: already exists
Copying blob 9b4c911e1bd7 skipped: already exists
Copying blob 6da302ea2369 skipped: already exists
Copying blob 4f4fb700ef54 skipped: already exists
Copying config d7b95427af done   |
Writing manifest to image destination
2024/05/08 13:46:36  info unpack layer: sha256:a486411936734b0d1d201c8a0ed8e9d449a64d5033fdc33411ec95bc26460efb
2024/05/08 13:46:36  info unpack layer: sha256:6da302ea23691726bc231ec4f1fc85654ae38567b65f92be0eff056ec1fec7fb
2024/05/08 13:46:40  info unpack layer: sha256:3e0f5a9f06fef2f919b49b617e6771f9a6881760a441982dff4d6219e140de5f
2024/05/08 13:46:45  info unpack layer: sha256:40fa5233cae50c8243acc9b78f6f165fbf9a9b0493bee7966a994768c1a9b47f
2024/05/08 13:46:45  info unpack layer: sha256:9b4c911e1bd794a157d42a2078e0fff6ca56343f7e2aaef55446683497dd6db1
2024/05/08 13:46:45  info unpack layer: sha256:595a0fe1a930d595b1bb1619f4f210a666a36522db2baf4078091c5bc2c195ba
2024/05/08 13:46:45  info unpack layer: sha256:4f4fb700ef54461cfa02571ae0db9a0dc1e0cdb5577484a6d75e68dc38e8acc1
INFO:    Creating SIF file...
(newconda)[becksts@awsgenomep] [/data/Sequence_analysis/Grandeur/Analyses/StJosephSelect_8May2024]
$ mv staphb-mashtree-1.4.6.img.pulling.1715194943310 /data/nextflow_cachedir/staphb-mashtree-1.4.6.img

**Comment by DrB-S** [comment]
Solved
