### ISSUE TITLE
Move from mast dist to mash screen 

### ISSUE THREAD

**Issue by erinyoung** [UPHL-BioNGS/Grandeur#26]
In version 3.0.230115, mash dist is used mostly to loosely flag samples for species-specific downstream tools. It could be more useful, and perhaps `mash screen` would help it be more useful.

**Comment by DrB-S** [comment]
Any progress on moving to mash screen?

**Comment by erinyoung** [comment]
It's still on my radar, but I need to finish https://github.com/UPHL-BioNGS/Donut_Falls/pull/9 first.

**Comment by erinyoung** [comment]
Actually, might just be moving to rdp
