### ISSUE TITLE
Rerunning iqtree2 with revised core_genome_alignment.aln

### ISSUE THREAD

**Issue by DrB-S** [UPHL-BioNGS/Grandeur#40]
Grandeur completed successfully, but I need to removed a couple taxa from the tree. I was able to modify both the snp matrix and core_genome_alignment.aln in the work directories, and I have removed the iqtree2 dir.

How can I rerun just that very last part of the pipeline? Is there something other than resume that I need to specify on the nextflow command-line?

**Comment by erinyoung** [comment]
I would recommend removing the files you don't want to include from your input. 

I don't know if just adding `-resume` to the command will use the edited work files or rerun them.

**Comment by DrB-S** [comment]
I did that as well, so I'll try resume.
