### ISSUE TITLE
Where is cg_pipeline_report.txt?

### ISSUE THREAD

**Issue by DrB-S** [UPHL-BioNGS/Grandeur#46]

**Comment by DrB-S** [comment]
Not pertinent to fasta files:-)

**Comment by erinyoung** [comment]
Yes, the cg-pipeline was replaced by [fastq-scan](https://github.com/rpetit3/fastq-scan).

Basically, I just wanted a tool to do coverage calculations and fastq-scan is much faster and has fewer steps. Plus, fastq-scan's results are in json, which is helpful to a lot of people.

There's a new version of fastqc out, though, and so fastq-scan might be replaced by an in-workflow script in an upcoming version.

**Comment by DrB-S** [comment]
OK. I'm all for faster! I was running a script on cg_pipeline_report to evaluate coverage and quality for each fastq, and advise whether or not to resequence. I'll change my script to use the fastq-scan output instead.
