### ISSUE TITLE
Too Few Core Genes Warning

### ISSUE THREAD

**Issue by whottel** [UPHL-BioNGS/Grandeur#77]
Hello,

I recently ran grandeur on a group of sequences that included a contaminated sample that threw off the SNP calculation as there were too few genes in the core genome (See attached roary summary).
[summary_statistics.txt](https://github.com/UPHL-BioNGS/Grandeur/files/11821741/summary_statistics.txt)
The iqtree folder was not created, but the snp-dist folder and matrix were still created despite the core gene count being well below the 1,500 cutoff you mention in the wiki. 
I was wondering if there was a more obvious way of alerting the user that the generated SNP matrix is unrealiable due to a low number of core genes or not create the matrix if this is the case. 

Thanks,
Wes

**Comment by erinyoung** [comment]
There might be something. I've thought about forcing the workflow to fail if there's no enough genes in the core genome, but that seems heavy handed.

The problem with having a contaminated sample, is that sometimes it's not easy to identify which one needs to be dropped (there's nothing in the roary output that indicates which sample is off), so it can be nice to have the SNP matrix to identify potential candidates.

**Comment by whottel** [comment]
Hi Erin,
I agree with what you are saying in that forcing the workflow to fail is probably too much. 
My issue was looking at the SNP matrix in this case (please find attached file) 
[snp_matrix.csv](https://github.com/UPHL-BioNGS/Grandeur/files/11837470/snp_matrix.csv)
it was not clear which sample was causing the issue, happened to be #33. 
Only when looking at the grandeur summary file did I notice there were both Klebsiella and Salmonella reads present for that sample. 
It is certainly on the user to check the relevant QC data when interpreting results, but maybe a brief txt file in the snp-dists folder that warns the user if the core gene count is below 1,500 or whatever other appropriate cutoff.

Thanks,
Wes

**Comment by erinyoung** [comment]
I think I have an idea.

What if there was an inclusion of the genome size and core genome length in the snp-dists header?

So in the first column would be snp-dists version n-genes: X genome-length: Y,sample1,sample2

**Comment by whottel** [comment]
That sounds good to me.

**Comment by erinyoung** [comment]
I think I have a solution. In https://github.com/UPHL-BioNGS/Grandeur/pull/84 there are some new features from SNP-dists. Once this PR passes testing, it will get merged into main and be part of Grandeur version 3.2.20230711.

They include a file called
- snp-dists/roary_metrics_mqc.csv - which is a summary of the roary metrics in the snp dists directory. It includes the number of samples, the number of genes in the core genome, and an approximate length of the core genome.
- snp-dists/snp_matrix_with_qc.txt - is the same as snp-dists/snp_matrix.txt with the header changed slightly to include the information found in roary_metrics_mqc.csv

Let me know if these are helpful!

**Comment by whottel** [comment]
Thanks, I find the changes in version 3.2.20230711 very helpful!
